### ISSUE TITLE
clean up the comments

### ISSUE THREAD

**Issue by aexbrown** [Behavioural-Genomics/tracking#2]

**Comment by ver228** [comment]
Done!

**Comment by ver228** [comment]
@aexbrown

**Comment by ver228** [comment]
@KezhiLi

**Comment by KezhiLi** [comment]
- [x] @mentions, #refs, [links](), **formatting**, and <del>tags</del> supported
- [x] list syntax required (any unordered or ordered list supported)
- [x] this is a complete item
- [x] this is an incomplete item

**Comment by KezhiLi** [comment]
https://github.com/Behavioural-Genomics/tracking/blob/master/tracking_bgnd_MP2.py#L234
